server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 #不限制请求体大小，默认2M

spring:
  application:
    name: gateway-service
  profiles:
    active: dev #dev-本地开发环境；prod-生产环境；test-测试环境

#日志级别
logging:
  level:
    root: info

blackIP:
  continueCounts: 5 #ip联系请求的次数
  timeInterval: 15 #ip判断的时间间隔，单位：秒
  limitTimes: 25 #黑名单ip限制的时间，单位：秒