spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #todo 线上环境的ip需要修改
        username: nacos
        password: nacos


