server:
  port: 66
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 #不限制请求体大小，默认2M

spring:
  application:
    name: main-service
  profiles:
    active: dev #dev-本地开发环境；prod-生产环境；test-测试环境


#日志级别
logging:
  level:
    root: info